#!/usr/bin/env python3
"""Derive the stride-2 stem conv structural sections from the differential
index remints, and emit the constants both packers embed.

Method: two Apple compiles of the SAME geometry with two payload bases
(uint16(i+1), and uint16(i+1) xor 0x4B1D). A byte offset holding element i
carries different bytes in the two views; every offset where the two views
AGREE is structural (geometry-constant, payload-independent). The retained
sections verify this: all 2560 elements map to exactly one offset each
(uniqueness), and the two views agree byte-for-byte everywhere else.

  python3 research/derive_strided_s2_sections.py   # regenerates both outputs

Outputs:
- research/strided_s2_structural.json  — base64 templates the python
  packers in mint_conv_probes.py load.
- plugins/H13/H13StridedS2Sections.inc — the same bytes as C arrays for
  packConvStridedMultitapS2 / packConvStridedDepthwiseS2.
"""
from __future__ import annotations

import base64
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MASK = 0x4B1D

CASES = {
    "dense": ("encoder_conv_idx_c1_n256_k3x3_s2_g1_bias1_same_x3000x128",
              "encoder_conv_idxb_c1_n256_k3x3_s2_g1_bias1_same_x3000x128",
              6144),
    "depthwise": ("encoder_conv_idx_c256_n256_k3x3_s2_g256_bias1_same_x1500x64",
                  "encoder_conv_idxb_c256_n256_k3x3_s2_g256_bias1_same_x1500x64",
                  7168),

}

ELEMENTS = 2304 + 256  # weight [256,1,3,3] then bias [256]


def derive(pair: tuple[str, str, int], tag: str) -> dict:
    stem_a, stem_b, size = pair
    da = (ROOT / "research/oracles/h13" / f"{stem_a}.const.bin").read_bytes()
    db = (ROOT / "research/oracles/h13" / f"{stem_b}.const.bin").read_bytes()
    if size is None:
        size = len(da)
    if len(da) != size or len(db) != size:
        raise SystemExit(f"{tag}: retained sections are {len(da)}/{len(db)} "
                         f"bytes, the records decode {size}")
    mapping = {}
    for i in range(ELEMENTS):
        pa = struct.pack("<H", (i + 1) & 0xFFFF)
        pb = struct.pack("<H", ((i + 1) ^ MASK) & 0xFFFF)
        pos_a = {p for p in range(size - 1) if da[p:p + 2] == pa}
        pos_b = {p for p in range(size - 1) if db[p:p + 2] == pb}
        common = pos_a & pos_b
        if len(common) != 1:
            raise SystemExit(f"{tag}: element {i} maps to {sorted(common)[:4]}")
        mapping[i] = common.pop()
    positions = sorted(mapping.values())
    if len(set(positions)) != ELEMENTS:
        raise SystemExit(f"{tag}: mapped positions are not unique")
    # The structural template: the section bytes the payload does not
    # occupy. Proof burden: outside the mapped windows the two views must
    # agree byte-for-byte (they do), so the template is view-independent;
    # inside the windows the packer overwrites whatever is here.
    structural = bytearray(da)
    covered = bytearray(size)
    for p in mapping.values():
        covered[p] = 1
        covered[p + 1] = 1
    for i in range(size):
        if not covered[i] and da[i] != db[i]:
            raise SystemExit(f"{tag}: views disagree at structural byte {i}")
    agree = sum(1 for i in range(size) if not covered[i] and da[i] == db[i])
    print(f"{tag}: {ELEMENTS} elements uniquely mapped, "
          f"{size - sum(covered)} structural bytes (all view-agreeing), "
          f"{sum(covered)} bytes in payload windows, "
          f"{size - agree - sum(covered)} of those byte-identical payload"
          f" artifacts")
    return {
        "structural": base64.b64encode(bytes(structural)).decode(),
        "size": size,
    }


def main() -> int:
    result = {tag: derive(pair, tag) for tag, pair in CASES.items()}
    # The encoder's third subsampling stage (750->375 g256) shares the
    # depthwise packing: identical structural bytes, identical payload
    # window pattern (verified against its own differential remints
    # encoder_conv_idx{,b}_c256_n256_k3x3_s2_g256_bias1_same_x750x32).
    stem = "c256_n256_k3x3_s2_g256_bias1_same_x750x32"
    da = (ROOT / "research/oracles/h13" /
          f"encoder_conv_idx_{stem}.const.bin").read_bytes()
    db = (ROOT / "research/oracles/h13" /
          f"encoder_conv_idxb_{stem}.const.bin").read_bytes()
    depthwise = base64.b64decode(result["depthwise"]["structural"])
    for i in range(len(da)):
        if da[i] != db[i]:
            continue  # payload window: the packer overwrites it
        assert da[i] == depthwise[i], f"stage-3 structural differs at {i}"
    print("depthwise375: structural template identical to depthwise - same packer")
    out_json = ROOT / "research/strided_s2_structural.json"
    out_json.write_text(json.dumps({
        "mask": MASK,
        "source": "receipts/2026-09-19-encoder-mask-oracles (differential index remints)",
        **result,
    }, indent=1))
    inc = ["// Generated by research/derive_strided_s2_sections.py from the",
           "// 2026-09-19 differential index remints — do not edit by hand.",
           "#pragma once", "#include <cstdint>", "#include <cstddef>", ""]
    for tag, data in result.items():
        payload = base64.b64decode(data["structural"])
        name = (f"kStridedS2{'Dense' if tag == 'dense' else 'Depthwise'}"
                f"Structural")
        inc.append(f"static constexpr std::uint8_t {name}[] = {{")
        for start in range(0, len(payload), 16):
            chunk = payload[start:start + 16]
            inc.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        inc.append("};")
        inc.append(
            f"static constexpr std::size_t {name}Size = "
            f"std::size({name});")
        inc.append("")
    out_inc = ROOT / "plugins/H13/H13StridedS2Sections.inc"
    out_inc.write_text("\n".join(inc) + "\n")
    print(f"wrote {out_json} and {out_inc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
