#!/usr/bin/env python3
"""Generate the H13 tile template table from oracle captures.

Tile is materialized: one task, input and output as distinct bindings, and
the const-x twin keeps the unexpanded input payload in the constant
section. Each decoded capture becomes one entry keyed by (input CHW, reps,
const-input flag) with the words replayed verbatim and the constant
section retained where the capture carries one.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAPTURES = ROOT / "research" / "oracles" / "h13" / "layout"


def reconstruct_task(td):
    words = [int(w, 16) for w in td["header_words"]]
    flat = {}
    for block in td["blocks"].values():
        for a, v in block["words"].items():
            flat[int(a, 16)] = int(v, 16)
    for rec in td["records"]:
        words.append(int(rec["header"], 16))
        base = int(rec["address"], 16)
        for index in range(rec["count"]):
            words.append(flat[base + index * 4])
    return words


def derive(path):
    record = json.loads(path.read_text())
    if record.get("error") or not record.get("task_descriptors"):
        return None
    tasks = [reconstruct_task(t) for t in record["task_descriptors"]]
    words = [w for task in tasks for w in task]
    const_bin = path.parent / (path.stem + ".const.bin")
    constants = const_bin.read_bytes() if const_bin.exists() else bytes(
        record["constant_section"]["size"])
    if len(constants) != record["constant_section"]["size"]:
        raise SystemExit(f"{path.name}: const size mismatch")
    params = record["parameters"]
    result_shape = list(params["result_shape"])
    while len(result_shape) < 4 and result_shape[:1] == [1]:
        result_shape = result_shape[1:]
    while len(result_shape) < 4:
        result_shape = [1] + result_shape
    assert len(result_shape) == 4 and result_shape[0] == 1
    shape = list(params["shape"])
    while len(shape) < 4 and shape[:1] == [1]:
        shape = shape[1:]
    while len(shape) < 4:
        shape = [1] + shape
    assert len(shape) == 4 and shape[0] == 1
    return {
        "words": words,
        "sizes": [len(t) for t in tasks],
        "constants": constants,
        "in_channels": shape[1],
        "in_height": shape[2],
        "in_width": shape[3],
        "reps": list(params["reps"][-3:]),
        "out": result_shape[1:],
        "constInput": path.stem.endswith("_b_idx") or
        path.stem.startswith("tile_b_"),
    }


def words_literal(name, words):
    lines = [f"static const uint32_t {name}[] = {{"]
    for off in range(0, len(words), 6):
        chunk = words[off:off + 6]
        lines.append("    " + ", ".join(f"0x{w:08x}" for w in chunk) + ",")
    lines.append("};")
    return lines


def main():
    entries = []
    for path in sorted(CAPTURES.glob("tile_*.json")):
        entry = derive(path)
        if entry is None:
            continue
        entry["stem"] = path.stem
        entries.append(entry)
    print(f"verified {len(entries)} entries")

    out = ["// Generated by research/generate_tile_tables.py from",
           "// research/oracles/h13/layout/ — do not edit by hand.",
           "#pragma once",
           "",
           "struct H13TileTemplate {",
           "    std::uint32_t inChannels, inHeight, inWidth;",
           "    std::uint32_t repChannels, repHeight, repWidth;",
           "    bool constInput;",
           "    std::uint32_t outChannels, outHeight, outWidth;",
           "    const std::uint32_t *words;",
           "    std::size_t wordCount;",
           "    const std::uint8_t *constants;",
           "    std::size_t constantBytes;",
           "    const std::uint32_t *taskWords;",
           "    std::size_t taskCount;",
           "};",
           ""]
    table = []
    for index, entry in enumerate(entries):
        wname = f"kTileWords{index}"
        cname = f"kTileConst{index}"
        sname = f"kTileSizes{index}"
        out.extend(words_literal(wname, entry["words"]))
        data = ", ".join(f"0x{b:02x}" for b in entry["constants"])
        out.append(f"static const uint8_t {cname}[] = {{{data}}};")
        out.append(f"static const uint32_t {sname}[] = "
                   f"{{{', '.join(map(str, entry['sizes']))}}};")
        out.append("")
        in_c, in_h, in_w = (entry["in_channels"], entry["in_height"],
                            entry["in_width"])
        rep_c, rep_h, rep_w = entry["reps"]
        out_c, out_h, out_w = entry["out"]
        table.append(
            "    {%d, %d, %d, %d, %d, %d, %s, %d, %d, %d, %s, "
            "std::size(%s), %s, std::size(%s), %s, std::size(%s)},"
            % (in_c, in_h, in_w, rep_c, rep_h, rep_w,
               "true" if entry["constInput"] else "false",
               out_c, out_h, out_w, wname, wname, cname, cname,
               sname, sname))
    out.append("static const H13TileTemplate kTileTasks[] = {")
    out.extend("    " + row for row in table)
    out.append("};")
    destination = ROOT / "plugins" / "H13" / "H13TileTemplates.inc"
    destination.write_text("\n".join(out) + "\n")
    print(f"wrote {destination}")


if __name__ == "__main__":
    main()
